os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - cd chess_timer
  - ../flutter/bin/flutter test
  - ../flutter/bin/flutter -v build apk
cache:
  directories:
    - $HOME/.pub-cache